name: Build QMK Firmware

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install QMK
        run: |
          python3 -m pip install qmk

      - name: Build firmware from QMK Configurator JSON
        run: |
          qmk compile dumbpad_v1x_oled_layout_2025-10-18.json

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: qmk-firmware
          path: "*.hex"
